'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Frupal.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Actions_application_exit_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_application_exit_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property binoculars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binoculars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackberry_bushes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackberry_bushes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property center_bg_menustrip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_bg_menustrip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chainsaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chainsaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chisel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chisel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downClick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downClick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Binoculars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Binoculars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Blackberry_Bushes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Blackberry_Bushes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_boulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_boulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Chainsaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Chainsaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Chisel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Chisel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Hatchet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Hatchet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Jackhammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Jackhammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Machete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Machete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Power_Bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Power_Bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Royal_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Royal_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Sledge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Sledge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Treasure_Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Treasure_Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest_Tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_Tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forest1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frupal_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frupal_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frupal_bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frupal_bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property game_won() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_won", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GameOverBg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GameOverBg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hatchet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hatchet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jackhammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackhammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jackhammer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackhammer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property knight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("knight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left__1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leftClick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leftClick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leftHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leftHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property machete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("machete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_binoculars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_binoculars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Blackberry_Bushes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Blackberry_Bushes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Boulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Boulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Chainsaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Chainsaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Chisel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Chisel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Hatchet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Hatchet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Jackhammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Jackhammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Machete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Machete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Power_Bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Power_Bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Royal_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Royal_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_sledge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_sledge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Treasure_Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Treasure_Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow_Tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow_Tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meadow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meadow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_strip_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_strip_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property None() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("None", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OrangeTree_archigraphs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OrangeTree_archigraphs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property powerbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rightClick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rightClick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rightHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rightHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property royal_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("royal_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sledge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sledge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startingGame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startingGame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property titleBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titleBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treasure_chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treasure_chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upClick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upClick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_binoculars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_binoculars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_blackberry_bushes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_blackberry_bushes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_boulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_boulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_chainsaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_chainsaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_chisel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_chisel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_hatchetl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_hatchetl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_jackhammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_jackhammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_machete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_machete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_power_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_power_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Water_Royal_Diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Water_Royal_Diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_Sledge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_Sledge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_Treasure_Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_Treasure_Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water_Tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_Tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
